version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-shoppingList-v1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: shoppingList
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-shoppingList-v1
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin1234
    ports:
      - "8090:80"